Add missing include statement for ssize_t
Compilation of code which uses libtiff fails when ssize_t is undefined:

openjpeg/thirdparty/libtiff/tif_config.h:324:22:
 error: unknown type name ‘ssize_t’
 #define TIFF_SSIZE_T ssize_t
                      ^
openjpeg/thirdparty/libtiff/tiffio.h:67:9: note:
 in expansion of macro ‘TIFF_SSIZE_T’
 typedef TIFF_SSIZE_T tmsize_t;
         ^

Add the missing include statement (not for Windows
which does not provide unistd.h).

Signed-off-by: Stefan Weil <sw@weilnetz.de>